### ISSUE TITLE
PHP Warning:  Invalid argument supplied for foreach() in /・・・/VkCssOptimize.php on line 472'

### ISSUE THREAD

**Issue by kurudrive** [vektor-inc/vk-css-optimize#12]
wordpressにてlightningを使用しているのですが、数日前から毎日、エラーログに以下のようなエラーが表示されます。
ーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーー
AH01071: Got error 'PHP message: PHP Warning:  Invalid argument supplied for foreach() in /・・・/VkCssOptimize.php on line 423
PHP message: PHP Warning:  Invalid argument supplied for foreach() in /・・・/VkCssOptimize.php on line 472'
ーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーーー
テーマ内のphpファイルだと思うのですが、どのように対処すればよろしいでしょうか。
ご教授宜しくお願い致します

https://vektor-vws.slack.com/archives/C01E6UDGNFN/p1675402773934219

**Comment by drill-lancer** [comment]
多分 https://github.com/vektor-inc/vk-css-optimize/pull/11 で治ってるはず・・・

**Comment by kurudrive** [comment]
@drill-lancer 
foreach の問題だから 
https://github.com/vektor-inc/vk-css-optimize/pull/13
で対応しないとあかんのっちゃう（・ｗ・？

**Comment by drill-lancer** [comment]
foreach に入ってくる as の前の変数は空の配列で初期化されているのでエラーが出なくなるという寸法です。

**Comment by drill-lancer** [comment]
・・・でもわかりやすく書いておくのも手だとは思ったのでマージします。

**Comment by kurudrive** [comment]
対応済み close
